/**
 * One-command Zeppole stack: generate secrets, start Docker Compose (autopilot overlay).
 * Usage: node scripts/zeppole-up.mjs [--reset] [--reset-runtime]
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const root = path.resolve(import.meta.dirname, "..");
const envFile = path.join(root, "zeppole.autopilot.env");

function randomHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

function randomPassword() {
  const alphabet = "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789";
  let s = "";
  for (let i = 0; i < 16; i++) s += alphabet[crypto.randomInt(alphabet.length)];
  return s;
}

function writeEnvIfMissing() {
  if (fs.existsSync(envFile)) {
    console.info(`Using existing secrets file: ${envFile}`);
    return false;
  }
  const jwt = randomHex(32);
  const bridgeTok = randomHex(24);
  const adminPass = randomPassword();
  const lines = [
    `# Generated by scripts/zeppole-up.mjs — do not commit`,
    `JWT_SECRET=${jwt}`,
    `ZEPPOLE_EMULATOR_BRIDGE_TOKEN=${bridgeTok}`,
    `ZEPPOLE_IMAGE_BUILDER_TOKEN=${bridgeTok}`,
    `BRIDGE_TOKEN=${bridgeTok}`,
    `ZEPPOLE_ADMIN_EMAIL=admin@zeppole.local`,
    `ZEPPOLE_ADMIN_PASSWORD=${adminPass}`,
    `ZEPPOLE_PUBLIC_HOST=localhost`,
    `ZEPPOLE_PUBLIC_SCHEME=http`,
    ``,
  ];
  fs.writeFileSync(envFile, lines.join("\n"), { mode: 0o600 });
  console.info(`Created ${envFile}`);
  console.info("");
  console.info("  Web UI:      http://localhost:8080");
  console.info("  Sign in as:  admin@zeppole.local");
  console.info(`  Password:    ${adminPass}`);
  console.info("");
  console.info("  (Same password is stored as ZEPPOLE_ADMIN_PASSWORD in that file.)");
  console.info("");
  return true;
}

function hostHasKvm() {
  try {
    fs.accessSync("/dev/kvm");
    return true;
  } catch {
    return false;
  }
}

function composeArgs(extra) {
  const files = ["docker-compose.yml", "docker-compose.autopilot.yml"];
  if (hostHasKvm()) {
    files.push("docker-compose.kvm.yml");
    console.info("Host has /dev/kvm — including docker-compose.kvm.yml for emulator-bridge");
  }
  return [
    "compose",
    ...files.flatMap((f) => ["-f", f]),
    "--env-file",
    "zeppole.autopilot.env",
    "--profile",
    "emulators",
    "--profile",
    "builders",
    "--profile",
    "with-worker",
    ...extra,
  ];
}

const args = process.argv.slice(2);
if (args.includes("--reset")) {
  console.info("Stopping stack and removing volumes (full reset)…");
  spawnSync("docker", composeArgs(["down", "-v"]), { cwd: root, stdio: "inherit", shell: true });
  try {
    fs.unlinkSync(envFile);
  } catch {
    /* ok */
  }
  console.info("Removed zeppole.autopilot.env (will be recreated on next up).");
}

if (args.includes("--reset-runtime")) {
  console.info("Removing worker token volume only…");
  spawnSync(
    "docker",
    ["volume", "rm", "-f", "zeppole_shared_runtime"],
    { cwd: root, stdio: "inherit", shell: true },
  );
}

const createdNew = writeEnvIfMissing();

const up = spawnSync("docker", composeArgs(["up", "-d", "--build"]), {
  cwd: root,
  stdio: "inherit",
  shell: true,
});

if (up.status !== 0) {
  process.exit(up.status ?? 1);
}

if (!createdNew && !args.includes("--reset")) {
  console.info("");
  console.info(`Stack is up. Credentials are in ${envFile} (ZEPPOLE_ADMIN_EMAIL / ZEPPOLE_ADMIN_PASSWORD).`);
  console.info("Web UI: http://localhost:8080");
}

console.info("");
console.info("Emulators: UI → Emulators (Docker bridge is wired). Execution worker uses an auto-issued device token.");
console.info("To wipe only the worker token volume: node scripts/zeppole-up.mjs --reset-runtime && node scripts/zeppole-up.mjs");
